name: Deploy and Update Index

on:
  push:
    branches:
      - main

jobs:
  deploy_and_update_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Glassy.zip SHA256 and Date in index.yml
        run: |
          chmod +x update_index.sh
          ./update_index.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust this to match the directory containing your GitHub Pages content
