name: Deploy and Update Index

on:
  push:
    branches:
      - main

jobs:
  deploy_and_update_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Glassy.zip SHA256 and Date in index.yml
        run: |
          # Generate SHA256 hash for Glassy.zip
          sha256_hash=$(sha256sum Glassy.zip | cut -d ' ' -f 1)

          # Update index.yml with new SHA256 hash and current date
          sed -i "s/sha256: .*/sha256: $sha256_hash/" index.yml
          sed -i "s/date: .*/date: \"$(date +"%Y-%m-%d %H:%M:%S")\"/" index.yml

          # Print the updated index.yml for verification
          cat index.yml

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

    # Additional GitHub Actions setup
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
    - uses: actions/deploy-pages@v4

    # Permissions
    permissions:
      id-token: write
